language: python

sudo: false

stages:
  - test
  - bundle
  - name: deploy
    if: tag =~ /^v\d+\.\d+\.\d+$/ AND repo = HaaLeo/swarmlib

install:
  - pip install -r requirements-dev.txt

script: pylint swarmlib

jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
    - stage: test
      python: 3.8

    - stage: bundle
      script: python setup.py sdist bdist_wheel
      python: 3.8

    - stage: deploy
      python: 3.8
      before_deploy:
        - cp {ThirdPartyNotices.txt,LICENSE.txt} ./swarmlib
        - python setup.py sdist bdist_wheel
        - twine upload dist/* -u HaaLeo -p ${PYPI_PASSWORD}
      script: skip
      deploy:
        provider: releases
        file_glob: true
        file: "dist/*"
        api_key: ${TRAVIS_CD}
        skip_cleanup: true
        on:
          tags: true
