name: Lint, Test, Bundle and Deploy

on:
  push:
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  lint-test-bundle:
    name: Lint, test and bundle
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: make install
      - name: Run Linter
        run: make lint
      - name: Run Unit Tests
        run: make test
      - name: Bundle Package
        run: make bundle
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: Coverage for swarmlib@${{ github.sha }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: swarmlib@${{ github.sha }}
          path: dist
          if-no-files-found: error

  verify-bundle:
    name: Verify bundle on ${{ matrix.os }} with python ${{ matrix.python }}
    needs:
      - lint-test-bundle
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Checkout Source # To get Makefile
        uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: swarmlib@${{ github.sha }}
          path: dist
      - name: Install and verify local swarmlib wheel
        run: make install-bundle

  publish:
    name: Publish Pypi Package
    needs:
      - lint-test-bundle
      - verify-bundle
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: swarmlib@${{ github.sha }}
          path: dist
      - name: Get Release Parameters
        id: getParameters
        run: |
          upload_url=$(curl -sL https://api.github.com/repos/${{github.repository}}/releases/latest?access_token=${{ secrets.GITHUB_TOKEN }} | jq -r '.upload_url')
          tarball_name=$(find ${{ steps.download.outputs.download-path }} -type f -name '*.tar.gz' -exec basename {} ';')
          wheel_name=$(find ${{ steps.download.outputs.download-path }} -type f -name '*.whl' -exec basename {} ';')
          echo ::set-output name=upload_url::$upload_url
          echo ::set-output name=tarball_name::$tarball_name
          echo ::set-output name=wheel_name::$wheel_name
      - name: Upload Release Asset (Tarball)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.getParameters.outputs.upload_url }}
          asset_path: ${{ steps.download.outputs.download-path }}/${{steps.getParameters.outputs.tarball_name}}
          asset_name: ${{steps.getParameters.outputs.tarball_name}}
          asset_content_type: application/x-gzip
      - name: Upload Release Asset (Wheel)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.getParameters.outputs.upload_url }}
          asset_path: ${{ steps.download.outputs.download-path }}/${{steps.getParameters.outputs.wheel_name}}
          asset_name: ${{steps.getParameters.outputs.wheel_name}}
          asset_content_type: application/zip
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ${{ steps.download.outputs.download-path }}
